# Generated by Django 6.0.4 on 2026-04-27 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(choices=[('blood', 'Blood Test'), ('urine', 'Urine Test'), ('xray', 'X-Ray'), ('mri', 'MRI Scan'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('general', 'General Checkup'), ('other', 'Other')], default='general', max_length=20)),
                ('report_date', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('detected_condition', models.CharField(blank=True, max_length=300)),
                ('symptoms', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('doctor_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzed', 'Analyzed'), ('reviewed', 'Doctor Reviewed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='7-Day Personalized Diet Plan', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan', to='health_app.medicalreport')),
            ],
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='health_app.patient'),
        ),
        migrations.CreateModel(
            name='ReportQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(upload_to='qrcodes/')),
                ('qr_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='health_app.medicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.TextField(blank=True)),
                ('lifestyle_changes', models.TextField(blank=True)),
                ('exercises', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('avoid_foods', models.TextField(blank=True)),
                ('avoid_activities', models.TextField(blank=True)),
                ('recommended_foods', models.TextField(blank=True)),
                ('followup_in_days', models.PositiveIntegerField(default=7)),
                ('additional_notes', models.TextField(blank=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='health_app.medicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='DietDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7')])),
                ('breakfast', models.TextField()),
                ('mid_morning', models.TextField(blank=True)),
                ('lunch', models.TextField()),
                ('evening', models.TextField(blank=True)),
                ('dinner', models.TextField()),
                ('water_intake', models.CharField(default='8-10 glasses', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='health_app.dietplan')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('diet_plan', 'day_number')},
            },
        ),
    ]
